<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-2H3V8ME1" name="com.lmg_dubai.sahlastore.inventory.Inventory_Send_Return_STC010" tests="1" failures="1" timestamp="2020-04-13T23:15:47 IST" time="137.657" errors="0">
  <testcase name="stc010" time="137.657" classname="com.lmg_dubai.sahlastore.inventory.Inventory_Send_Return_STC010">
    <failure type="java.lang.AssertionError" message="unable to Click on &#039;To location field&#039;">
      <![CDATA[java.lang.AssertionError: unable to Click on 'To location field'
at org.testng.Assert.fail(Assert.java:97)
at com.lmg_dubai.sahlasell.util.MobileActionUtil.clickElement(MobileActionUtil.java:288)
at com.lmg_dubai.sahlasell.pages.InventorySendCreateReturnPage.verifyToLocPopup(InventorySendCreateReturnPage.java:69)
at com.lmg_dubai.sahlasell.pages.InventorySendCreateReturnPage.createReturnRequest(InventorySendCreateReturnPage.java:95)
at com.lmg_dubai.sahlastore.inventory.Inventory_Send_Return_STC010.stc010(Inventory_Send_Return_STC010.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- stc010 -->
  <system-out/>
</testsuite> <!-- com.lmg_dubai.sahlastore.inventory.Inventory_Send_Return_STC010 -->
