<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-2H3V8ME1" name="com.lmg_dubai.sahlastore.inventory.Inventory_Send_Return_STC009" tests="1" failures="1" timestamp="2020-04-21T10:07:53 IST" time="159.820" errors="0">
  <testcase name="stc009" time="159.820" classname="com.lmg_dubai.sahlastore.inventory.Inventory_Send_Return_STC009">
    <failure type="java.lang.AssertionError" message="expected [Dispatched] but found [Pending]">
      <![CDATA[java.lang.AssertionError: expected [Dispatched] but found [Pending]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:563)
at com.lmg_dubai.sahlasell.pages.InventorySendStoreTransferPage.selectStatusFromFilter(InventorySendStoreTransferPage.java:405)
at com.lmg_dubai.sahlasell.pages.InventorySendStoreTransferPage.verifyFilterStatusOptions(InventorySendStoreTransferPage.java:416)
at com.lmg_dubai.sahlastore.inventory.Inventory_Send_Return_STC009.stc009(Inventory_Send_Return_STC009.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- stc009 -->
  <system-out/>
</testsuite> <!-- com.lmg_dubai.sahlastore.inventory.Inventory_Send_Return_STC009 -->
